# Generated by Django 4.0.5 on 2022-07-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
